# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: marketplace_development

test:
  <<: *default
  database: marketplace_test

production:
  <<: *default
  database: marketplace_production
